
project_id = "fmcymhdtudjohlabpvob"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 15
max_client_conn = 100

[realtime]
enabled = false

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = false
port = 54324

[storage]
enabled = false

[auth]
enabled = true
site_url = "https://796dd99a-3ea0-4c7e-af8f-5ceb1e2c6528.lovableproject.com"
additional_redirect_urls = ["https://localhost:3000"]

[auth.email]
enable_signup = true

[functions.fetch-conversation]
verify_jwt = true

[functions.fetch-emails]
verify_jwt = true

[functions.fetch-imap-emails]
verify_jwt = true

[functions.mark-as-read]
verify_jwt = true

[functions.send-email]
verify_jwt = true

[functions.test-mailbox-connection]
verify_jwt = true

[functions.update-conversation-status]
verify_jwt = true

[functions.update-email-status]
verify_jwt = true
