// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmcymhdtudjohlabpvob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtY3ltaGR0dWRqb2hsYWJwdm9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMTIwNjIsImV4cCI6MjA1OTg4ODA2Mn0.NZNQXGAUcEqSBIjSjm7NDSM8wzBJbWRDtC-ZZemXGnM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);